spring:
  application:
    name: redis-demo
  data:
    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          max-idle: 8
          min-idle: 1
          max-active: 20
          max-wait: 5s
